
FROM nginx:latest

# Set the working directory to the default location where Nginx serves content
WORKDIR /usr/share/nginx/html

# Copy the custom index.html file to the Nginx HTML directory
COPY index.html ./index.html

# Expose port 80 to the outside world
EXPOSE 80
