apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster # The name of the StatefulSet that manages the Elasticsearch cluster
spec:
  serviceName: elasticsearch-cluster # The name of the service that governs the StatefulSet
  replicas: 1 # Number of replicas (Elasticsearch nodes) to run in the cluster
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        resources:
          limits:
            memory: "1000M"
            cpu: "200m"
        ports:
        - containerPort: 9200 # Port for the REST API
          name: rest # Name for the port
          protocol: TCP # Protocol used for communication
        - containerPort: 9300 # Port for inter-node communication
          protocol: TCP # Protocol used for communication
          name: transport # Name for the port
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: discovery.type # Environment variable to specify the discovery type
          value: "single-node" # Setting this to single-node for testing; change for production
        - name: cluster.name # Environment variable to specify the cluster name
          value: "elasticsearch-cluster" # Name of the Elasticsearch cluster
      initContainers: # Init containers run before the main containers
      - name: fix-permissions # Init container to fix permissions on data directory
        image: busybox:1.31.1 # Lightweight image for running commands
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"] # Change ownership of the data directory
        securityContext:
          privileged: true # Granting privileged access to the init container
        volumeMounts:
        - name: data # Reference to the same volume
          mountPath: /usr/share/elasticsearch/data # Mount path for the data directory
      - name: increase-fd-ulimit # Init container to increase file descriptor limit
        image: busybox:1.31.1 # Lightweight image for running commands
        command: ["sh", "-c", "ulimit -n 65536"] # Increase the number of open file descriptors
        securityContext:
          privileged: true # Granting privileged access to the init container
      volumeClaimTemplates: # Template for persistent volume claims
      - metadata:
          name: data # Name of the volume claim
          labels:
            app: elasticsearch # Labels for the volume claim
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch # Name of the service to expose Elasticsearch
  labels:
    app: elasticsearch # Labels for the service
spec:
  selector:
    app: elasticsearch # Selector to route traffic to the pods with this label
  clusterIP: None
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: inter-node
