apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: two-tier
spec:
  clusterIP: None
  selector:
    app: my-sql
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
spec:
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-sql-config
  namespace: two-tier
data:
  MY_SQL_USER: root
  MY_SQL_DB_NAME: mydb

