- name: Download Required Packages 
  become: yes 
  gather_facts: true 
  vars:
    packages:  
    - python 
    - openjdk-11-jdk
    - maven
    - ansible-lint
    - docker.io
    - docker-compose
    - wget 
    - unzip 
  tasks: 
  - name: Install Required Packages 
    ansible.builtin.apt:
     name: "{{ item }}"
     state: present
    with_items: "{{packages}}"
    async: 60
    retries: 3
    delay: 10
    until: ansible.builtin.package_is_installed(name=item)
    notify: 
    - Restart Docker
  handlers:
  - name: Restart Docker
    ansible.builtin.service:
     name: docker
     state: restarted
     enabled: yes
     ignore_errors: yes

