- name: Install Nginx
  hosts: all
  become: yes 
  gather_facts: true 
  tasks:
   - name: Install NGINX on DEBIAN BASED 
     ansible.builtin.apt:
      name: nginx
      state: present
     when: gather_facts['os_family'] == 'Debian'
   - name: Install NGINX on Redhat BASED 
     ansible.builtin.yum:
      name: nginx
      state: present
     when: gather_facts['os_family'] == 'Redhat'
   -  name: Start Nginx 
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
  